name: Deploy to Ec2 instance 

on: 
  push:
    branch: [ main ]

jobs:
    build-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build



    deploy:
      needs: [build-test]
      runs-on: ubuntu-latest

      steps:
        - name: SSH deploy
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ secrets.HOST }}
            username:  ${{ secrets.USER }}
            key:  ${{ secrets.KEY }}
            port: 22
            passphrase: 12345678
            script: |
                curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
                . ~/.nvm/nvm.sh
                nvm instal 16
                npm install -g pm2
                cd ~/nextapp
                git pull origin main
                npm install
                npm run build
                pm2 restart nextapp

