name: Deploy to Ec2 instance 

on: 
  push:
    branch: [ master]

jobs:
    build-test:
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
          with:
            node-version: 14
      - run: npm install
      - run: npm run build